- src/main/java/org/example/todotravel/domain/chat/entity/ChatRoom.java
- src/main/java/org/example/todotravel/domain/chat/entity/ChatRoomDetail.java
- src/main/java/org/example/todotravel/domain/chat/entity/Message.java
- src/main/java/org/example/todotravel/domain/notification/entity/Alarm.java
- src/main/java/org/example/todotravel/domain/plan/entity/Budget.java
- src/main/java/org/example/todotravel/domain/plan/entity/Comment.java
- src/main/java/org/example/todotravel/domain/plan/entity/Like.java
- src/main/java/org/example/todotravel/domain/plan/entity/Plan.java
- src/main/java/org/example/todotravel/domain/plan/entity/PlanUser.java
- src/main/java/org/example/todotravel/domain/plan/entity/Schedule.java
- src/main/java/org/example/todotravel/domain/plan/entity/Vehicle.java
- src/main/java/org/example/todotravel/domain/user/entity/Follow.java
- src/main/java/org/example/todotravel/domain/user/entity/Gender.java
- src/main/java/org/example/todotravel/domain/user/entity/Role.java
- src/main/java/org/example/todotravel/domain/user/entity/User.java
> Feat: entity 기본 베이스 설정

- src/main/java/org/example/todotravel/domain/chat/entity/ChatRoom.java
- src/main/java/org/example/todotravel/domain/chat/entity/ChatRoomDetail.java
- src/main/java/org/example/todotravel/domain/chat/entity/Message.java
- src/main/java/org/example/todotravel/domain/notification/entity/Alarm.java
- src/main/java/org/example/todotravel/domain/plan/entity/Bookmark.java
- src/main/java/org/example/todotravel/domain/plan/entity/Budget.java
- src/main/java/org/example/todotravel/domain/plan/entity/Comment.java
- src/main/java/org/example/todotravel/domain/plan/entity/Location.java
- src/main/java/org/example/todotravel/domain/plan/entity/Plan.java
- src/main/java/org/example/todotravel/domain/plan/entity/PlanUser.java
- src/main/java/org/example/todotravel/domain/plan/entity/Schedule.java
- src/main/java/org/example/todotravel/domain/plan/entity/Vehicle.java
- src/main/java/org/example/todotravel/domain/user/entity/Follow.java
- src/main/java/org/example/todotravel/domain/user/entity/User.java
> Feat: Plan entity 수정 완료

- src/main/java/org/example/todotravel/global/exception/UserNotFoundException.java
- src/main/java/org/example/todotravel/global/handler/ErrorDetails.java
- src/main/java/org/example/todotravel/global/handler/GlobalExceptionHandler.java
> Feat: 사용자 정의 예외처리 기초 설정

- src/main/java/org/example/todotravel/domain/chat/entity/ChatRoom.java
- src/main/java/org/example/todotravel/domain/chat/entity/ChatRoomDetail.java
- src/main/java/org/example/todotravel/domain/chat/entity/Message.java
@Data 대신 @Getter @Setter 사용으로 수정.
채팅에서 플랜 참조.
> Feat: 채팅 엔티티 수정 3차

- build.gradle
- src/main/java/org/example/todotravel/domain/plan/controller/LocationController.java
- src/main/java/org/example/todotravel/domain/plan/dto/request/LocationRequestDto.java
- src/main/java/org/example/todotravel/domain/plan/dto/request/ScheduleRequestDto.java
- src/main/java/org/example/todotravel/domain/plan/entity/Location.java
- src/main/java/org/example/todotravel/domain/plan/entity/Plan.java
- src/main/java/org/example/todotravel/domain/plan/entity/PlanUser.java
- src/main/java/org/example/todotravel/domain/plan/entity/Schedule.java
- src/main/java/org/example/todotravel/domain/plan/implement/LocationServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/implement/ScheduleServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/repository/LocationRepository.java
- src/main/java/org/example/todotravel/domain/plan/repository/ScheduleRepository.java
- src/main/java/org/example/todotravel/domain/plan/service/LocationService.java
- src/main/java/org/example/todotravel/domain/plan/service/ScheduleService.java
- src/main/java/org/example/todotravel/domain/user/entity/Follow.java
- src/main/java/org/example/todotravel/global/controller/ApiResponse.java
JPA 문제 오류 해결
위치 검색 후 좌표값으로 위치 저장하기
> Feat: entity 오류 수정 완료, 위치 검색 및 저장 기능 완료

- src/main/java/org/example/todotravel/domain/plan/controller/PlanController.java
- src/main/java/org/example/todotravel/domain/plan/dto/request/PlanRequestDto.java
- src/main/java/org/example/todotravel/domain/plan/entity/Plan.java
- src/main/java/org/example/todotravel/domain/plan/implement/PlanServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/repository/PlanRepository.java
- src/main/java/org/example/todotravel/domain/plan/service/PlanService.java
plan 생성, 수정, 삭제 구현
코드나 프로젝트 구성 확인해주세요!!
어떤 변경 사항이 있나요?
> Feat: plan 생성, 수정, 삭제 구현

- src/main/java/org/example/todotravel/domain/user/controller/UserController.java
- src/main/java/org/example/todotravel/domain/user/dto/request/LoginRequestDto.java
- src/main/java/org/example/todotravel/domain/user/dto/response/LoginResponseDto.java
- src/main/java/org/example/todotravel/domain/user/service/UserService.java
- src/main/java/org/example/todotravel/domain/user/service/impl/UserServiceImpl.java
- src/main/java/org/example/todotravel/global/handler/GlobalExceptionHandler.java
- src/main/java/org/example/todotravel/global/security/jwt/filter/JwtAuthenticationFilter.java
- src/test/java/org/example/todotravel/TodotravelApplicationTests.java
일반 로그인에 따른 토큰 발급
1. 역할을 불러오는 Claim 키 값 수정
2. 일반 회원가입 사용자 로그인 기능
3. Access Token 재발급 로직 추가
어떤 변경 사항이 있나요?
> Feat: 일반 로그인에 따른 토큰 발급 기능

- src/main/java/org/example/todotravel/domain/plan/controller/PlanController.java
- src/main/java/org/example/todotravel/domain/plan/controller/PlanUserController.java
- src/main/java/org/example/todotravel/domain/plan/repository/PlanUserRepository.java
- src/main/java/org/example/todotravel/domain/plan/service/PlanService.java
- src/main/java/org/example/todotravel/domain/plan/service/PlanUserService.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanUserServiceImpl.java
테스트 해보고 정상 작동하지 않는 부분 수정
전체 틀에서는 큰 변화 없이 세부적인 코드만 변경되었습니다.
어떤 변경 사항이 있나요?
> Fix: 플랜 생성, 수정, 삭제, 초대 기능 수정

- src/main/java/org/example/todotravel/domain/plan/controller/BookmarkController.java
- src/main/java/org/example/todotravel/domain/plan/controller/LikeController.java
- src/main/java/org/example/todotravel/domain/plan/controller/PlanController.java
- src/main/java/org/example/todotravel/domain/plan/dto/response/PlanListResponseDto.java
- src/main/java/org/example/todotravel/domain/plan/dto/response/PlanResponseDto.java
- src/main/java/org/example/todotravel/domain/plan/entity/Bookmark.java
- src/main/java/org/example/todotravel/domain/plan/entity/Like.java
- src/main/java/org/example/todotravel/domain/plan/repository/BookmarkRepository.java
- src/main/java/org/example/todotravel/domain/plan/repository/LikeRepository.java
- src/main/java/org/example/todotravel/domain/plan/repository/PlanRepository.java
- src/main/java/org/example/todotravel/domain/plan/service/BookmarkService.java
- src/main/java/org/example/todotravel/domain/plan/service/LikeService.java
- src/main/java/org/example/todotravel/domain/plan/service/PlanService.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/BookmarkServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/LikeServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanServiceImpl.java
- src/main/java/org/example/todotravel/global/jwt/filter/JwtAuthenticationFilter.java
- 플랜 목록 조회 기능
- 플랜 조회 기능
- 북마크, 좋아요 기능
- 플랜 불러오기 기능
플랜 보기 관련 기능 구현
어떤 변경 사항이 있나요?
> Feat: 플랜 보기 관련 기능 구현

- src/main/java/org/example/todotravel/domain/user/controller/UserController.java
- src/main/java/org/example/todotravel/domain/user/dto/request/OAuth2UserLoginRequestDto.java
- src/main/java/org/example/todotravel/domain/user/entity/User.java
- src/main/java/org/example/todotravel/domain/user/service/UserService.java
- src/main/java/org/example/todotravel/domain/user/service/impl/UserServiceImpl.java
- src/main/java/org/example/todotravel/global/config/SecurityConfig.java
- src/main/java/org/example/todotravel/global/oauth2/CustomOAuth2User.java
- src/main/java/org/example/todotravel/global/oauth2/OAuthAttributes.java
- src/main/java/org/example/todotravel/global/oauth2/handler/OAuth2LoginFailureHandler.java
- src/main/java/org/example/todotravel/global/oauth2/handler/OAuth2LoginSuccessHandler.java
- src/main/java/org/example/todotravel/global/oauth2/service/CustomOAuth2UserService.java
- src/main/java/org/example/todotravel/global/oauth2/userinfo/GoogleOAuth2UserInfo.java
- src/main/java/org/example/todotravel/global/oauth2/userinfo/KakaoOAuth2UserInfo.java
- src/main/java/org/example/todotravel/global/oauth2/userinfo/NaverOAuth2UserInfo.java
- src/main/java/org/example/todotravel/global/oauth2/userinfo/OAuth2UserInfo.java
Feat: OAuth2 로그인 기능, 추가정보 로직 생성, 
Fix: User - social_type 수정
OAuth2 로그인 기능까지는 성공했는데,
프론트 연동 뒤에 테스트 한번 더 해봐야합니다.
그리고 User에 Social_type null이 들어올 수 있게 수정했습니다.
어떤 변경 사항이 있나요?
- [] 문서 수정
> Feat: OAuth2 로그인 기능, 추가정보 로직 생성, Fix: User - social_type 수정

- src/main/java/org/example/todotravel/global/config/SecurityConfig.java
Security 프론트 연동을 위한 CORS 설정
어떤 변경 사항이 있나요?
> Refactor: Security 프론트 연동을 위한 CORS 설정

- src/main/java/org/example/todotravel/global/jwt/filter/JwtAuthenticationFilter.java
JWT 필터 경로 재설정
없앴던거 다시 필요할거 같아서 만들었습니다..
어떤 변경 사항이 있나요?
> Refactor: JWT 필터 재설정

- build.gradle
- src/main/java/org/example/todotravel/domain/user/controller/UserController.java
- src/main/java/org/example/todotravel/domain/user/entity/User.java
- src/main/java/org/example/todotravel/global/config/SecurityConfig.java
- src/main/java/org/example/todotravel/global/jwt/filter/JwtAuthenticationFilter.java
- src/main/java/org/example/todotravel/global/oauth2/handler/OAuth2LoginSuccessHandler.java
- src/main/java/org/example/todotravel/global/oauth2/service/CustomOAuth2UserService.java
- src/main/resources/static/index.html
OAuth2 관련 부분 Security부분하고 다 수정했습니다.
OAuth2 관련 부분 Security부분하고 다 수정했습니다.
어떤 변경 사항이 있나요?
> Fix: OAuth2 연관 파일 수정

- src/main/java/org/example/todotravel/domain/chat/controller/ChatController.java
- src/main/java/org/example/todotravel/domain/chat/service/impl/ChatServiceImpl.java
- src/test/java/org/example/todotravel/domain/chat/controller/ChatControllerTest.java
- src/test/java/org/example/todotravel/domain/chat/service/impl/ChatServiceImplTest.java
ApiResponse 사용
RuntimeException로 변경
ChatController에서 ApiResponse 사용
ChatServiceImpl RuntimeException으로 변경
어떤 변경 사항이 있나요?
> Feat: 채팅방 수정 2차

- src/main/java/org/example/todotravel/domain/user/controller/TokenController.java
- src/main/java/org/example/todotravel/domain/user/controller/UserController.java
- src/main/java/org/example/todotravel/domain/user/dto/response/LoginResponseDto.java
- src/main/java/org/example/todotravel/global/jwt/util/JwtTokenizer.java
Refresh Token만 쿠키로 재설정
일단 일반 회원가입, 로그인 테스트는 완료하였고,
재발급 부분은 구현은 했는데, 추후 프론트에서 다른 컴포넌트로 접속해봐야 할 것 같습니다.
어떤 변경 사항이 있나요?
> Refactor: Refresh Token만 쿠키로 재설정

- src/main/java/org/example/todotravel/domain/plan/service/implement/BookmarkServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/LikeServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanUserServiceImpl.java
기존의 알림 자동생성 기능 추가 완료
어떤 변경 사항이 있나요?
> Feat: 알림 자동 생성 처리 완료 - 플랜 초대, 북마크, 좋아요, 플랜 수정

- src/main/java/org/example/todotravel/domain/chat/controller/ChatRoomController.java
- src/main/java/org/example/todotravel/domain/chat/dto/request/OneToOneChatRoomRequestDto.java
- src/main/java/org/example/todotravel/domain/chat/dto/response/ChatRoomResponseDto.java
- src/main/java/org/example/todotravel/domain/chat/entity/ChatRoom.java
- src/main/java/org/example/todotravel/domain/chat/repository/ChatRoomRepository.java
- src/main/java/org/example/todotravel/domain/chat/service/ChatRoomService.java
- src/main/java/org/example/todotravel/domain/chat/service/impl/ChatRoomServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/controller/PlanController.java
- src/main/java/org/example/todotravel/domain/plan/controller/PlanUserController.java
- src/main/java/org/example/todotravel/global/config/SecurityConfig.java
1. 1:1 채팅방 생성 및 플랜-채팅방 동시 수행 부분 추가
2. ChatRoomRepository JPA 오류 해결
3. 채팅방 생성 오류 해결
4. 채팅방 나가기 요청이 안받아지는 오류 해결
일부는 테스트 했지만, 전부는 못해서 오늘 단위 테스트 진행 예정입니다.
어떤 변경 사항이 있나요?
> Feat & Fix : 1:1 채팅방 생성 및 플랜-채팅방 동시 수행 부분 추가

- build.gradle
- src/main/java/org/example/todotravel/domain/user/controller/UserController.java
- src/main/java/org/example/todotravel/domain/user/dto/response/LoginResponseDto.java
- src/main/java/org/example/todotravel/domain/user/entity/EmailMessage.java
- src/main/java/org/example/todotravel/domain/user/entity/RefreshToken.java
- src/main/java/org/example/todotravel/global/jwt/util/JwtTokenizer.java
- src/test/java/org/example/todotravel/domain/user/service/impl/EmailServiceImplTest.java
- src/test/java/org/example/todotravel/domain/user/service/impl/RefreshTokenServiceImplTest.java
- src/test/java/org/example/todotravel/domain/user/service/impl/UserServiceImplTest.java
- src/test/java/org/example/todotravel/global/jwt/util/JwtTokenizerTest.java
1. 테스트를 위한 의존성 추가
2. 토큰 생성 / 파싱 테스트 코드 추가
3. 사용자 인증, 토큰, 이메일 서비스단 테스트 코드 추가
4. UserController 코드 리팩토링
어떤 변경 사항이 있나요?
> Test, Refactor : 서비스단 테스트 코드 추가 및 리팩토링

- src/main/java/org/example/todotravel/domain/plan/controller/PlanUserController.java
PlanUser 관련 무한 참조 문제 해결
이제 더 이상의 무한 참조는 없습니다..!!! 후..
어떤 변경 사항이 있나요?
> Fix: PlanUser 무한 참조 문제 해결

- src/main/java/org/example/todotravel/domain/user/controller/UserController.java
- src/main/java/org/example/todotravel/domain/user/dto/request/OAuth2AdditionalInfoRequestDto.java
- src/main/java/org/example/todotravel/domain/user/service/impl/UserServiceImpl.java
- src/main/java/org/example/todotravel/global/config/SecurityConfig.java
- src/main/java/org/example/todotravel/global/jwt/util/JwtTokenizer.java
- src/main/java/org/example/todotravel/global/oauth2/handler/OAuth2LoginSuccessHandler.java
OAuth2 부분 프론트와 연동을 위한 수정
프론트에서 일반 회원가입 시에는 refreshToken을 쿠키로 잘 받아오는데,
OAuth2 로그인 시에는 refreshToken이 쿠키에 없는 부분은 해결해야 합니다.
일단 작동은 해서 PR 올립니다.
어떤 변경 사항이 있나요?
> Refactor: OAuth2 프론트와 연동을 위한 수정

- src/main/java/org/example/todotravel/global/oauth2/handler/OAuth2LoginFailureHandler.java
- src/main/java/org/example/todotravel/global/oauth2/service/CustomOAuth2UserService.java
OAuth2 다른 소셜 이메일 중복시의 처리 수정
어떤 변경 사항이 있나요?
> Feat/server : OAuth2 다른 소셜 이메일 중복시의 처리 수정

- build.gradle
- src/main/java/org/example/todotravel/domain/chat/controller/ChatMessageController.java
- src/main/java/org/example/todotravel/domain/chat/controller/ChatRoomController.java
- src/main/java/org/example/todotravel/domain/chat/dto/request/ChatMessageRequestDto.java
- src/main/java/org/example/todotravel/domain/chat/dto/response/ChatMessageResponseDto.java
- src/main/java/org/example/todotravel/domain/chat/entity/ChatMessage.java
- src/main/java/org/example/todotravel/domain/chat/entity/ChatRoomUser.java
- src/main/java/org/example/todotravel/domain/chat/repository/ChatMessageRepository.java
- src/main/java/org/example/todotravel/domain/chat/service/ChatMessageService.java
- src/main/java/org/example/todotravel/domain/chat/service/impl/ChatMessageServiceImpl.java
- src/main/java/org/example/todotravel/global/config/MongoDBConfig.java
- src/main/java/org/example/todotravel/global/config/SecurityConfig.java
- src/main/java/org/example/todotravel/global/config/WebConfig.java
- src/main/java/org/example/todotravel/global/config/WebSocketConfig.java
cors 부분 webconfig로 대체했습니다.
채팅 부분 기본 로직 제작했스비낟.
아직 기초단계라 뒤에 리팩토링 해야할 것 같습니다.
어떤 변경 사항이 있나요?
> Feat: 기본 채팅 로직 추가, 수정

- src/main/java/org/example/todotravel/domain/plan/controller/PlanController.java
- src/main/java/org/example/todotravel/domain/plan/dto/request/PlanRequestDto.java
- src/main/java/org/example/todotravel/domain/plan/dto/response/PlanListResponseDto.java
- src/main/java/org/example/todotravel/domain/plan/dto/response/PlanResponseDto.java
- src/main/java/org/example/todotravel/domain/plan/dto/response/PlanUserResponseDto.java
- src/main/java/org/example/todotravel/domain/plan/entity/Plan.java
- src/main/java/org/example/todotravel/domain/plan/service/PlanService.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanServiceImpl.java
- src/main/java/org/example/todotravel/domain/user/service/UserService.java
- src/main/java/org/example/todotravel/domain/user/service/impl/UserServiceImpl.java
- src/main/java/org/example/todotravel/global/jwt/token/JwtAuthenticationToken.java
- Plan의 LocalDateTime -> LocalDate로 변경
- 로그인 정보 받아오는 부분 플랜 생성에 구현(전체에는 아직 반영하지 않음)
- ResponseDto에 nickname 추가
pull 받으시고 db에서 오류나면 plans 한번 drop해주세요!!
어떤 변경 사항이 있나요?
> Fix, Refactor: 프론트 구현 중 발생한 변경사항

- src/main/java/org/example/todotravel/global/config/SecurityConfig.java
- src/main/java/org/example/todotravel/global/oauth2/OAuthAttributes.java
Feat: OAUTH2 GOOGLE 로그인 추가
OAUTH2 부분만 간단하게 추가했습니다.
yml 추가적으로 해야합니다~
어떤 변경 사항이 있나요?
> Feat: OAUTH2 GOOGLE 로그인 추가

- src/main/java/org/example/todotravel/domain/user/controller/EmailController.java
- src/main/java/org/example/todotravel/domain/user/controller/UserController.java
- src/main/java/org/example/todotravel/domain/user/dto/request/PasswordResetRequestDto.java
- src/main/java/org/example/todotravel/domain/user/dto/request/PasswordSearchRequestDto.java
- src/main/java/org/example/todotravel/domain/user/dto/response/PasswordSearchResponseDto.java
- src/main/java/org/example/todotravel/domain/user/dto/response/UsernameResponseDto.java
- src/main/java/org/example/todotravel/domain/user/repository/UserRepository.java
- src/main/java/org/example/todotravel/domain/user/service/UserService.java
- src/main/java/org/example/todotravel/domain/user/service/impl/EmailServiceImpl.java
- src/main/java/org/example/todotravel/domain/user/service/impl/UserServiceImpl.java
- src/main/java/org/example/todotravel/global/config/SecurityConfig.java
- src/test/java/org/example/todotravel/domain/user/service/impl/EmailServiceImplTest.java
- src/test/java/org/example/todotravel/domain/user/service/impl/UserServiceImplTest.java
1. 임시 비밀번호 발급 로직 제거 및 인증번호 숫자 6자리로 변경
2. 아이디, 비밀번호 찾기 시 이메일 인증을 사용하도록 추가
3. 아이디 찾기 수정 및 비밀번호 재설정 추가
어떤 변경 사항이 있나요?
> Feat/server : 아이디/비밀번호 찾기를 위한 수정 및 추가

- src/main/java/org/example/todotravel/domain/chat/controller/ChatRoomController.java
- src/main/java/org/example/todotravel/domain/plan/controller/BookmarkController.java
- src/main/java/org/example/todotravel/domain/plan/controller/LikeController.java
- src/main/java/org/example/todotravel/domain/plan/controller/PlanController.java
- src/main/java/org/example/todotravel/domain/plan/repository/BookmarkRepository.java
- src/main/java/org/example/todotravel/domain/plan/repository/LikeRepository.java
- src/main/java/org/example/todotravel/domain/plan/service/BookmarkService.java
- src/main/java/org/example/todotravel/domain/plan/service/LikeService.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/BookmarkServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/LikeServiceImpl.java
- 플랜 삭제 구현
- 북마크, 좋아요 여부 조회 구현
플랜 삭제는 cascade 문제로 아직 잘 돌아가지는 않습니다.. 돌려보실 때 참고해주세요.
어떤 변경 사항이 있나요?
> Feat: 북마크, 좋아요 여부 조회 구현

- src/main/java/org/example/todotravel/domain/user/controller/EmailController.java
- src/main/java/org/example/todotravel/domain/user/controller/TokenController.java
- src/main/java/org/example/todotravel/domain/user/controller/UserController.java
- src/main/java/org/example/todotravel/domain/user/service/impl/EmailServiceImpl.java
- src/main/java/org/example/todotravel/global/config/SecurityConfig.java
- src/main/java/org/example/todotravel/global/handler/ErrorDetails.java
- src/main/java/org/example/todotravel/global/handler/GlobalExceptionHandler.java
1. 프론트에 던져주는 메시지 변경
2. 특정 요청 HTTP 메서드 수정
3. 토큰 갱신 오류 수정
Security에 의해 토큰이 만료된 경우 /login으로 무한리다이렉트 되는 부분 해결했습니다.
어떤 변경 사항이 있나요?
> Feat/server : 토큰 갱신 오류 수정

- src/main/java/org/example/todotravel/domain/plan/controller/PlanController.java
Plan 도메인 및 메소드 변경
어떤 변경 사항이 있나요?
> Feat: Refactoring

- src/main/java/org/example/todotravel/domain/chat/controller/ChatMessageController.java
- src/main/java/org/example/todotravel/domain/chat/repository/ChatRoomUserRepository.java
- src/main/java/org/example/todotravel/domain/chat/service/impl/ChatMessageServiceImpl.java
- Refactor: 채팅 메시지 서비스 로직 주석, 코드 수정
- 메시지 부분은 이제 다 완료했습니다, 채팅방 추가 api같은 경우는 추후에 추가 해야합니다~
어떤 변경 사항이 있나요?
> Refactor: 채팅 메시지 서비스 로직 주석, 코드 수정

- src/main/java/org/example/todotravel/domain/user/controller/UserController.java
- Refactor: 유저 컨트롤러 RequestParam 수정
컨트롤러 부분 requestparam이 정상적으로 작동 안되어서 수정했습니다.
어떤 변경 사항이 있나요?
> Refactor: 유저 컨트롤러 RequestParam 수정

- src/main/java/org/example/todotravel/domain/plan/dto/response/PlanSummaryDto.java
- src/main/java/org/example/todotravel/domain/plan/repository/BookmarkRepository.java
- src/main/java/org/example/todotravel/domain/plan/repository/LikeRepository.java
- src/main/java/org/example/todotravel/domain/plan/repository/PlanUserRepository.java
- src/main/java/org/example/todotravel/domain/plan/service/CommentService.java
- src/main/java/org/example/todotravel/domain/plan/service/PlanService.java
- src/main/java/org/example/todotravel/domain/plan/service/PlanUserService.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/CommentServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanUserServiceImpl.java
- src/main/java/org/example/todotravel/domain/user/controller/MypageController.java
- src/main/java/org/example/todotravel/domain/user/dto/request/UserInfoRequestDto.java
- src/main/java/org/example/todotravel/domain/user/dto/response/MyProfileResponseDto.java
- src/main/java/org/example/todotravel/domain/user/dto/response/UserProfileResponseDto.java
- src/main/java/org/example/todotravel/domain/user/entity/User.java
- src/main/java/org/example/todotravel/domain/user/service/UserService.java
- src/main/java/org/example/todotravel/domain/user/service/impl/UserServiceImpl.java
- src/main/java/org/example/todotravel/global/jwt/util/AuthenticationUtil.java
1. 마이페이지 - 프론트에 넘길 정보 추가
2. 사용자를 찾는 쿼리문 줄이도록 수정
3. 여행 수가 참여한 여행 수가 되도록 수정
4. DTO 전환 시 여행 생성자 닉네임이 들어가도록 수정
5. 사용자 소개글에 대한 추가
마이페이지 지금까지 한 것 한 번에 하기보다 미리 PR 올리는게 좋을 것 같아 올립니다.
어떤 변경 사항이 있나요?
> Feat/Refactor: 마이페이지 기능 추가 및 약간의 리팩토링

- src/main/java/org/example/todotravel/domain/plan/service/PlanUserService.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanUserServiceImpl.java
- src/main/java/org/example/todotravel/domain/user/controller/MypageController.java
- src/main/java/org/example/todotravel/domain/user/dto/response/MyProfileResponseDto.java
- src/main/java/org/example/todotravel/domain/user/dto/response/UserProfileResponseDto.java
- src/main/java/org/example/todotravel/domain/user/repository/FollowRepository.java
- src/main/java/org/example/todotravel/domain/user/service/FollowService.java
- src/main/java/org/example/todotravel/domain/user/service/impl/FollowServiceImpl.java
- src/main/java/org/example/todotravel/global/dto/PagedResponseDto.java
1. 프로필 조회 시 현재 팔로우 중인지에 대한 확인 추가
2. 팔로워 조회 시 무한스크롤을 위한 수정
여행은 특성상 일단은 플랜 양이 그리 많은 것은 아니니 페이지네이션으로 하지 않았고,
팔로우는 플랜 대비 많을 것으로 예상해서 페이지네이션으로 수정했습니다.
어떤 변경 사항이 있나요?
> Feat/Refactor: 팔로우 관련 추가 및 수정

- src/main/java/org/example/todotravel/domain/plan/repository/BookmarkRepository.java
- src/main/java/org/example/todotravel/domain/plan/repository/CommentRepository.java
- src/main/java/org/example/todotravel/domain/plan/repository/LikeRepository.java
- src/main/java/org/example/todotravel/domain/plan/service/BookmarkService.java
- src/main/java/org/example/todotravel/domain/plan/service/CommentService.java
- src/main/java/org/example/todotravel/domain/plan/service/LikeService.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/BookmarkServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/CommentServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/LikeServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanServiceImpl.java
cascade 문제로 삭제되지 않던 플랜 삭제 해결
어떤 변경 사항이 있나요?
> Fix: 플랜 삭제 기능 수정

- src/main/java/org/example/todotravel/domain/plan/controller/PlanController.java
- src/main/java/org/example/todotravel/domain/plan/dto/request/PlanThumbnailRequestDto.java
- src/main/java/org/example/todotravel/domain/plan/dto/response/PlanListResponseDto.java
- src/main/java/org/example/todotravel/domain/plan/entity/Plan.java
- src/main/java/org/example/todotravel/domain/plan/service/PlanService.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanServiceImpl.java
- src/main/java/org/example/todotravel/domain/user/service/impl/UserServiceImpl.java
- src/main/java/org/example/todotravel/global/aws/S3Service.java
- 플랜 썸네일 등록했습니다
- 플랜 썸네일 등록했습니다
어떤 변경 사항이 있나요?
> Feat : 플랜 썸네일 추가

- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanServiceImpl.java
Fix: 중괄호 지워진 것 복구
어떤 변경 사항이 있나요?
> Fix: 중괄호 지워진 것 복구

- src/main/java/org/example/todotravel/domain/plan/dto/response/CommentSummaryResponseDto.java
- src/main/java/org/example/todotravel/domain/plan/dto/response/PlanSummaryDto.java
- src/main/java/org/example/todotravel/domain/plan/repository/BookmarkRepository.java
- src/main/java/org/example/todotravel/domain/plan/repository/CommentRepository.java
- src/main/java/org/example/todotravel/domain/plan/repository/LikeRepository.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanServiceImpl.java
마이페이지에서도 플랜 썸네일을 반환하도록 수정했습니다.
어떤 변경 사항이 있나요?
> Refactor: 플랜 썸네일도 반환하도록 수정

- src/main/java/org/example/todotravel/domain/chat/dto/request/OneToOneChatRoomRequestDto.java
- src/main/java/org/example/todotravel/domain/plan/controller/PlanUserController.java
- src/main/java/org/example/todotravel/domain/plan/controller/RecruitmentController.java
- src/main/java/org/example/todotravel/domain/plan/dto/response/PlanListResponseDto.java
- src/main/java/org/example/todotravel/domain/plan/dto/response/PlanResponseDto.java
- src/main/java/org/example/todotravel/domain/plan/entity/Plan.java
- src/main/java/org/example/todotravel/domain/plan/repository/PlanRepository.java
- src/main/java/org/example/todotravel/domain/plan/repository/PlanUserRepository.java
- src/main/java/org/example/todotravel/domain/plan/service/PlanService.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanUserServiceImpl.java
- 플랜 모집 구현 및 필요한 속성 추가
- 플랜 참여자 관련 오류 해결
어떤 변경 사항이 있나요?
> Feat, Fix: 플랜 모집 구현 및 오류 수정

- src/main/java/org/example/todotravel/domain/plan/controller/VoteController.java
- src/main/java/org/example/todotravel/domain/plan/controller/VoteLogController.java
- src/main/java/org/example/todotravel/domain/plan/dto/request/VoteRequestDto.java
- src/main/java/org/example/todotravel/domain/plan/dto/response/VoteResponseDto.java
- src/main/java/org/example/todotravel/domain/plan/entity/Vote.java
- src/main/java/org/example/todotravel/domain/plan/entity/VoteLog.java
- src/main/java/org/example/todotravel/domain/plan/repository/VoteLogRepository.java
- src/main/java/org/example/todotravel/domain/plan/repository/VoteRepository.java
- src/main/java/org/example/todotravel/domain/plan/service/VoteLogService.java
- src/main/java/org/example/todotravel/domain/plan/service/VoteService.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/VoteLogServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/VoteServiceImpl.java
Vote 로직 추가
VoteLog (투표한 사용자들 정보를 가져오기 위해서 새로 추가함)
어떤 변경 사항이 있나요?
> Feat, Fix : Vote 구현 완료 및 세부 수정

- src/main/java/org/example/todotravel/domain/plan/controller/PlanController.java
- src/main/java/org/example/todotravel/domain/plan/controller/PlanUserController.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanServiceImpl.java
- 플랜 불러오기 오류 해결
- 플랜 나가기 오류 해결
어떤 변경 사항이 있나요?
> Fix: 플랜 불러오기, 플랜 나가기 오류 해결

- src/main/java/org/example/todotravel/domain/chat/repository/ChatRoomRepository.java
- src/main/java/org/example/todotravel/domain/chat/service/impl/ChatMessageServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/controller/PlanController.java
- src/main/java/org/example/todotravel/domain/plan/dto/request/PlanRequestDto.java
- src/main/java/org/example/todotravel/domain/plan/dto/response/PlanCountProjection.java
- src/main/java/org/example/todotravel/domain/plan/entity/Plan.java
- src/main/java/org/example/todotravel/domain/plan/repository/BookmarkRepository.java
- src/main/java/org/example/todotravel/domain/plan/repository/LikeRepository.java
- src/main/java/org/example/todotravel/domain/plan/repository/PlanRepository.java
- src/main/java/org/example/todotravel/domain/plan/repository/PlanUserRepository.java
- src/main/java/org/example/todotravel/domain/plan/service/BookmarkService.java
- src/main/java/org/example/todotravel/domain/plan/service/LikeService.java
- src/main/java/org/example/todotravel/domain/plan/service/PlanService.java
- src/main/java/org/example/todotravel/domain/plan/service/PlanUserService.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/BookmarkServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/LikeServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanUserServiceImpl.java
- src/main/java/org/example/todotravel/domain/user/controller/MypageController.java
- src/main/java/org/example/todotravel/domain/user/dto/response/MyProfileResponseDto.java
Refactor: 메시지 저장 시 roomDate 업데이트 되도록 수정
Refactor: 플랜 생성 시 행정구역도 저장되도록 수정 및 플랜 이미지 필수 제거
Feat: 마이페이지 모집 중인 플랜 항목 추가
Refactor: 플랜 조회 시 좋아요 및 북마크 수 카운팅 쿼리 최적화
어떤 변경 사항이 있나요?
> Feat/Refactor: 플랜 생성 시 행정구역 및 이미지 필수 제거 / 마이페이지 모집 중인 플랜 항목 추가 / 북마크, 좋아요 수 카운팅 쿼리 최적화

- src/main/java/org/example/todotravel/domain/plan/controller/PlanController.java
- src/main/java/org/example/todotravel/domain/plan/dto/response/PlanResponseDto.java
- src/main/java/org/example/todotravel/domain/plan/entity/Plan.java
- src/main/java/org/example/todotravel/domain/plan/repository/PlanRepository.java
- src/main/java/org/example/todotravel/domain/plan/service/PlanService.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanServiceImpl.java
- src/main/java/org/example/todotravel/domain/user/controller/MypageController.java
- src/main/java/org/example/todotravel/domain/user/controller/UserController.java
- src/main/java/org/example/todotravel/domain/user/dto/request/NicknameRequestDto.java
- src/main/java/org/example/todotravel/domain/user/dto/request/OAuth2AdditionalInfoRequestDto.java
- src/main/java/org/example/todotravel/domain/user/dto/request/PasswordResetRequestDto.java
- src/main/java/org/example/todotravel/domain/user/dto/request/PasswordUpdateRequestDto.java
- src/main/java/org/example/todotravel/domain/user/dto/request/UserRegisterRequestDto.java
- src/main/java/org/example/todotravel/domain/user/entity/User.java
- src/main/java/org/example/todotravel/global/handler/GlobalExceptionHandler.java
- 사용자 인증 관련 유효성 검증 추가
- 유효성 검증 오류에 대한 GlobalExceptionHandler 추가
- 플랜 수정 시 기존 이미지 삭제 및 수정이 가능하도록 수정
- 인기순 정렬을 위한 조회 수 컬럼 및 증가 메서드 생성
- 플랜 전체보기에 대한 행정구역, 도시, 최신순-인기순 기능 구현
플랜 생성, 복제 시 기본 값 들어가도록 추가했어요. 
플랜 전체보기 인기순 때문에 조회 수만 컬럼으로 넣었고, 프론트랑 테스트는 테스트 데이터 제대로 생성해보고 알려드리겠습니다 ! 일단 실행간에 문제는 없어요.
어떤 변경 사항이 있나요?
> Feat/Refactor : 플랜 전체보기에 대한 행정구역, 도시, 최신순-인기순 기능 / 유효성 검증 수정

- src/main/java/org/example/todotravel/domain/plan/controller/PlanController.java
- src/main/java/org/example/todotravel/domain/plan/controller/PlanUserController.java
- src/main/java/org/example/todotravel/domain/plan/controller/RecruitmentController.java
- src/main/java/org/example/todotravel/domain/plan/dto/response/PendingPlanUserDto.java
- src/main/java/org/example/todotravel/domain/plan/dto/response/PlanResponseDto.java
- src/main/java/org/example/todotravel/domain/plan/dto/response/PlanUserResponseDto.java
- src/main/java/org/example/todotravel/domain/plan/repository/PlanRepository.java
- src/main/java/org/example/todotravel/domain/plan/repository/PlanUserRepository.java
- src/main/java/org/example/todotravel/domain/plan/service/PlanService.java
- src/main/java/org/example/todotravel/domain/plan/service/PlanUserService.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanUserServiceImpl.java
- src/main/java/org/example/todotravel/domain/user/dto/response/UserListResponseDto.java
- 플랜 모집,취소 시 오류 해결
- 수락,거절을 위한 pending PlanUser 목록 구현
- 플랜 수정 시 frontLocation 오류 해결
- 플랜 모집 리스트 구현
플랜 모집, 취소 시 pending, rejected 상태인 PlanUser를 제거하도록 변경했습니다.
어떤 변경 사항이 있나요?
> Feat, Fix: 플랜 수정, 모집,취소 시 오류 해결 / 수락,거절을 위한 pending PlanUser 목록 구현 / 플랜 모집 리스트 구현

- src/main/java/org/example/todotravel/domain/notification/entity/Alarm.java
- src/main/java/org/example/todotravel/domain/notification/repository/AlarmRepository.java
- src/main/java/org/example/todotravel/domain/notification/service/implement/AlarmServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/dto/request/ScheduleCreateRequestDto.java
필요없는 부분 삭제 및
데일리 미팅 진행 후 alarm 변경
어떤 변경 사항이 있나요?
> Fix: Alarm 수정

- src/main/java/org/example/todotravel/domain/plan/controller/PlanController.java
- src/main/java/org/example/todotravel/domain/plan/controller/RecruitmentController.java
- src/main/java/org/example/todotravel/global/config/SecurityConfig.java
- 플랜 param 설정 및 권한 추가
- 모집 부분에서 프론트로 못받아와서 따로 추가했습니다.
어떤 변경 사항이 있나요?
> Feat/Refactor : 플랜 param 설정 및 권한 추가

- src/main/java/org/example/todotravel/domain/chat/dto/response/ChatMessageResponseDto.java
- src/main/java/org/example/todotravel/domain/plan/dto/response/PlanListResponseDto.java
- src/main/java/org/example/todotravel/domain/plan/repository/BookmarkRepository.java
- src/main/java/org/example/todotravel/domain/plan/repository/LikeRepository.java
- src/main/java/org/example/todotravel/domain/plan/repository/PlanRepository.java
- src/main/java/org/example/todotravel/domain/plan/repository/PlanUserRepository.java
- src/main/java/org/example/todotravel/domain/plan/service/BookmarkService.java
- src/main/java/org/example/todotravel/domain/plan/service/LikeService.java
- src/main/java/org/example/todotravel/domain/plan/service/PlanService.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/BookmarkServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/LikeServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanUserServiceImpl.java
- 각 채팅 메시지에 생성 날짜 포함되도록 추가
- 플랜 조회 시 각 플랜 생성자에 대한 N+1 조회 문제 해결
어떤 변경 사항이 있나요?
> Refactor : 플랜 조회 시 각 플랜 생성자에 대한 N+1 조회 문제 해결

- src/main/java/org/example/todotravel/domain/plan/controller/PlanController.java
- src/main/java/org/example/todotravel/domain/plan/controller/RecruitmentController.java
- 플랜 RequestParam 파라미터 이름 설정
- 프론트에서 오류나는 환경 수정했습니다, Param 이름 다 붙임.
어떤 변경 사항이 있나요?
> Feat: 플랜 RequestParam 파라미터 이름 설정

- src/main/java/org/example/todotravel/domain/plan/controller/PlanUserController.java
> Feat, Fix: 플랜 초대 가능 상태 추가

- src/main/java/org/example/todotravel/domain/user/controller/EmailController.java
- src/main/java/org/example/todotravel/domain/user/controller/MypageController.java
- src/main/java/org/example/todotravel/domain/user/controller/UserController.java
- src/main/java/org/example/todotravel/domain/user/service/RefreshTokenService.java
- src/main/java/org/example/todotravel/domain/user/service/UserService.java
- src/main/java/org/example/todotravel/domain/user/service/impl/RefreshTokenServiceImpl.java
- src/main/java/org/example/todotravel/domain/user/service/impl/UserServiceImpl.java
- src/main/java/org/example/todotravel/domain/user/service/impl/UserWithdrawalServiceImpl.java
- src/main/java/org/example/todotravel/global/jwt/util/JwtTokenizer.java
- src/test/java/org/example/todotravel/domain/user/service/impl/RefreshTokenServiceImplTest.java
Refactor: 사용자 인증 부분 메서드명 통일을 위한 수정
어떤 변경 사항이 있나요?
> Refactor: 사용자 인증 부분 메서드명 통일을 위한 수정

- src/main/java/org/example/todotravel/domain/chat/controller/ChatRoomController.java
- src/main/java/org/example/todotravel/domain/plan/controller/CommentController.java
- src/main/java/org/example/todotravel/domain/plan/controller/PlanController.java
- src/main/java/org/example/todotravel/domain/plan/controller/PlanUserController.java
- src/main/java/org/example/todotravel/domain/plan/controller/RecruitmentController.java
- src/main/java/org/example/todotravel/domain/plan/service/PlanService.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanServiceImpl.java
메소드명 통일을 위한 수정 - 플랜
어떤 변경 사항이 있나요?
> Fix, Refactor: 메소드명 통일을 위한 수정 - 플랜

- src/main/java/org/example/todotravel/domain/chat/controller/ChatMessageController.java
- src/main/java/org/example/todotravel/domain/chat/controller/ChatRoomController.java
- src/main/java/org/example/todotravel/domain/chat/service/ChatMessageService.java
- src/main/java/org/example/todotravel/domain/chat/service/ChatRoomService.java
- src/main/java/org/example/todotravel/domain/chat/service/impl/ChatMessageServiceImpl.java
- src/main/java/org/example/todotravel/domain/chat/service/impl/ChatRoomServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/controller/PlanController.java
- src/main/java/org/example/todotravel/domain/plan/controller/PlanUserController.java
- src/main/java/org/example/todotravel/domain/user/service/impl/UserWithdrawalServiceImpl.java
Refactor: 채팅 메소드 명 변경
어떤 변경 사항이 있나요?
> Refactor: 채팅 메소드 명 변경

- src/main/java/org/example/todotravel/domain/notification/controller/AlarmController.java
- src/main/java/org/example/todotravel/domain/notification/service/AlarmService.java
- src/main/java/org/example/todotravel/domain/notification/service/implement/AlarmServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/controller/LocationController.java
- src/main/java/org/example/todotravel/domain/plan/controller/ScheduleController.java
- src/main/java/org/example/todotravel/domain/plan/controller/VoteController.java
- src/main/java/org/example/todotravel/domain/plan/controller/VoteLogController.java
- src/main/java/org/example/todotravel/domain/plan/service/LocationService.java
- src/main/java/org/example/todotravel/domain/plan/service/ScheduleService.java
- src/main/java/org/example/todotravel/domain/plan/service/VoteService.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/LocationServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/ScheduleServiceImpl.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/VoteServiceImpl.java
- src/main/java/org/example/todotravel/domain/user/service/impl/UserWithdrawalServiceImpl.java
[Fix: Alarm, Scehdule, Location, Vote 메소드 명 변경](https://github.com/11dontcare/todotravel_backend/commit/23fa0150279e21653141f26ae2c81d83e0bd576b)
어떤 변경 사항이 있나요?
> Fix: Alarm, Scehdule, Location, Vote 메소드 명 변경

- build.gradle
Chore: build.gradle S3 의존성 수정
어떤 변경 사항이 있나요?
> Chore: build.gradle S3 의존성 수정

- deployment/appspec.yml
- deployment/scripts/start_nginx.sh
- src/main/java/org/example/todotravel/domain/plan/repository/PlanRepository.java
- src/main/java/org/example/todotravel/domain/plan/service/implement/PlanServiceImpl.java
- src/main/java/org/example/todotravel/global/jwt/util/JwtTokenizer.java
Fix: 플랜 검색 시 닉네임, 썸네일 추가
Chore: HTTPS를 위한 스크립트 추가
어떤 변경 사항이 있나요?
> Fix/Chore : 플랜 검색 시 닉네임, 썸네일 추가 / HTTPS를 위한 스크립트 추가

- src/main/java/org/example/todotravel/global/jwt/util/JwtTokenizer.java
Refactor : 쿠키 설정 추가
어떤 변경 사항이 있나요?
> Refactor : 쿠키 설정 추가

- src/main/java/org/example/todotravel/global/config/security/SecurityConfig.java
Fix: 토큰 재발급 안되는 문제 해결
어떤 변경 사항이 있나요?
> Fix: 토큰 재발급 안되는 문제 해결

- src/main/java/org/example/todotravel/domain/user/dto/request/PasswordResetRequestDto.java
- src/main/java/org/example/todotravel/domain/user/dto/request/PasswordUpdateRequestDto.java
- src/main/java/org/example/todotravel/domain/user/dto/request/UserRegisterRequestDto.java
Feat: 비밀번호에 대한 유효성 주석 제거
어떤 변경 사항이 있나요?
> Feat: 비밀번호에 대한 유효성 주석 제거

- src/main/java/org/example/todotravel/domain/plan/entity/Schedule.java
> Fix: 이동수단 선택지 지하철 추가

- src/main/java/org/example/todotravel/global/config/security/SecurityConfig.java
> !HOTFIX: Security Config 수정
